/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProjectsSlugIndexRouteImport } from './routes/_app/projects/$slug/index'
import { Route as AppProjectsSlugMembersRouteImport } from './routes/_app/projects/$slug/members'
import { Route as AppProjectsSlugMockRouteImport } from './routes/_app/projects/$slug/mock'
import { Route as AppProjectsSlugStandardRouteImport } from './routes/_app/projects/$slug/standard'
import { Route as AppProjectsSlugStandardHealthRouteImport } from './routes/_app/projects/$slug/standard-health'
import { Route as AppProjectsSlugVersionsVersionIdRouteImport } from './routes/_app/projects/$slug/versions/$versionId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugIndexRoute = AppProjectsSlugIndexRouteImport.update({
  id: '/projects/$slug/',
  path: '/projects/$slug/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugMembersRoute = AppProjectsSlugMembersRouteImport.update({
  id: '/projects/$slug/members',
  path: '/projects/$slug/members',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugMockRoute = AppProjectsSlugMockRouteImport.update({
  id: '/projects/$slug/mock',
  path: '/projects/$slug/mock',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugStandardRoute = AppProjectsSlugStandardRouteImport.update({
  id: '/projects/$slug/standard',
  path: '/projects/$slug/standard',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugStandardHealthRoute =
  AppProjectsSlugStandardHealthRouteImport.update({
    id: '/projects/$slug/standard-health',
    path: '/projects/$slug/standard-health',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsSlugVersionsVersionIdRoute =
  AppProjectsSlugVersionsVersionIdRouteImport.update({
    id: '/projects/$slug/versions/$versionId',
    path: '/projects/$slug/versions/$versionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/projects/$slug/members': typeof AppProjectsSlugMembersRoute
  '/projects/$slug/mock': typeof AppProjectsSlugMockRoute
  '/projects/$slug/standard': typeof AppProjectsSlugStandardRoute
  '/projects/$slug/standard-health': typeof AppProjectsSlugStandardHealthRoute
  '/projects/$slug/': typeof AppProjectsSlugIndexRoute
  '/projects/$slug/versions/$versionId': typeof AppProjectsSlugVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/projects/$slug/members': typeof AppProjectsSlugMembersRoute
  '/projects/$slug/mock': typeof AppProjectsSlugMockRoute
  '/projects/$slug/standard': typeof AppProjectsSlugStandardRoute
  '/projects/$slug/standard-health': typeof AppProjectsSlugStandardHealthRoute
  '/projects/$slug': typeof AppProjectsSlugIndexRoute
  '/projects/$slug/versions/$versionId': typeof AppProjectsSlugVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$slug/members': typeof AppProjectsSlugMembersRoute
  '/_app/projects/$slug/mock': typeof AppProjectsSlugMockRoute
  '/_app/projects/$slug/standard': typeof AppProjectsSlugStandardRoute
  '/_app/projects/$slug/standard-health': typeof AppProjectsSlugStandardHealthRoute
  '/_app/projects/$slug/': typeof AppProjectsSlugIndexRoute
  '/_app/projects/$slug/versions/$versionId': typeof AppProjectsSlugVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects/$slug/members'
    | '/projects/$slug/mock'
    | '/projects/$slug/standard'
    | '/projects/$slug/standard-health'
    | '/projects/$slug/'
    | '/projects/$slug/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/projects/$slug/members'
    | '/projects/$slug/mock'
    | '/projects/$slug/standard'
    | '/projects/$slug/standard-health'
    | '/projects/$slug'
    | '/projects/$slug/versions/$versionId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/projects/$slug/members'
    | '/_app/projects/$slug/mock'
    | '/_app/projects/$slug/standard'
    | '/_app/projects/$slug/standard-health'
    | '/_app/projects/$slug/'
    | '/_app/projects/$slug/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug/': {
      id: '/_app/projects/$slug/'
      path: '/projects/$slug'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof AppProjectsSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug/members': {
      id: '/_app/projects/$slug/members'
      path: '/projects/$slug/members'
      fullPath: '/projects/$slug/members'
      preLoaderRoute: typeof AppProjectsSlugMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug/mock': {
      id: '/_app/projects/$slug/mock'
      path: '/projects/$slug/mock'
      fullPath: '/projects/$slug/mock'
      preLoaderRoute: typeof AppProjectsSlugMockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug/standard': {
      id: '/_app/projects/$slug/standard'
      path: '/projects/$slug/standard'
      fullPath: '/projects/$slug/standard'
      preLoaderRoute: typeof AppProjectsSlugStandardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug/standard-health': {
      id: '/_app/projects/$slug/standard-health'
      path: '/projects/$slug/standard-health'
      fullPath: '/projects/$slug/standard-health'
      preLoaderRoute: typeof AppProjectsSlugStandardHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug/versions/$versionId': {
      id: '/_app/projects/$slug/versions/$versionId'
      path: '/projects/$slug/versions/$versionId'
      fullPath: '/projects/$slug/versions/$versionId'
      preLoaderRoute: typeof AppProjectsSlugVersionsVersionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsSlugMembersRoute: typeof AppProjectsSlugMembersRoute
  AppProjectsSlugMockRoute: typeof AppProjectsSlugMockRoute
  AppProjectsSlugStandardRoute: typeof AppProjectsSlugStandardRoute
  AppProjectsSlugStandardHealthRoute: typeof AppProjectsSlugStandardHealthRoute
  AppProjectsSlugIndexRoute: typeof AppProjectsSlugIndexRoute
  AppProjectsSlugVersionsVersionIdRoute: typeof AppProjectsSlugVersionsVersionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProjectsSlugMembersRoute: AppProjectsSlugMembersRoute,
  AppProjectsSlugMockRoute: AppProjectsSlugMockRoute,
  AppProjectsSlugStandardRoute: AppProjectsSlugStandardRoute,
  AppProjectsSlugStandardHealthRoute: AppProjectsSlugStandardHealthRoute,
  AppProjectsSlugIndexRoute: AppProjectsSlugIndexRoute,
  AppProjectsSlugVersionsVersionIdRoute: AppProjectsSlugVersionsVersionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
